name: Build and Release algo-ui

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'algo-ui/**'
      - '.github/workflows/algo_ui.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'algo-ui/**'
      - '.github/workflows/algo_ui.yml'
    tags:
      - "v*.*.*"   # e.g. v1.0.0
permissions:
  contents: write


jobs:
  flutter-checks:
    name: Flutter Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: algo-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Zip build artifacts
        run: |
          cd build
          zip -r web_build_${{ github.ref_name }}.zip web

  release:
    name: Release Build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: flutter-checks
    defaults:
      run:
        working-directory: algo-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Zip build artifacts
        run: |
          cd build
          zip -r web_build_${{ github.ref_name }}.zip web

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: algo-ui
      #     path: algo-ui/build/web
      
      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: algo-ui/build/web_build_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
