name: Build and Release

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'algo-ui/**'
      - '.github/workflows/build_and_release.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'algo-ui/**'
      - '.github/workflows/build_and_release.yml'
    tags:
      - "v*.*.*"   # e.g. v1.0.0

permissions:
  contents: write

jobs:
  build-algo-ui:
    name: Build and Test algo-ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: algo-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  build-algo-api:
    name: Build and Test algo-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: algo-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          python -m pytest

  release:
    name: Release Build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: 
      - build-algo-ui
      - build-algo-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'

      - name: Install dependencies
        run: |-
          cd algo-ui
          flutter pub get

      - name: Build Flutter Web
        run: |-
          cd algo-ui
          flutter build web --release

      - name: Zip algo-ui build artifacts
        run: |
          cd algo-ui/build
          zip -r algo_ui_${{ github.ref_name }}.zip web

      - name: Zip algo-api build artifacts
        run: |
          zip -r algo_api_${{ github.ref_name }}.zip algo-api
      
      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            algo-ui/build/algo_ui_${{ github.ref_name }}.zip
            algo_api_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
