name: Terraform OCI Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/terraform/**'
      - '.github/workflows/terraform-oci.yml'
  pull_request:
    branches: [ main ]
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    env:
      TF_VAR_tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaaxiav5vdqw5parmj53dqetb4syuh6kscguvuxix65xjqhcmtjdliq"
      TF_VAR_user_ocid: "ocid1.user.oc1..aaaaaaaaha5qlbilghe6jcs4hbfvkup2cgrzurc5uawkxgnmbdr4glric3bq"
      TF_VAR_fingerprint: "18:56:c7:01:bf:67:31:f4:03:69:ca:d6:30:a6:65:c7"
      TF_VAR_private_key_path: "oci_api_key.pem"
      TF_VAR_region: "ap-mumbai-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      OCI_KEY_FILE_CONTENT: ${{ secrets.OCI_KEY_FILE_CONTENT }}

      # Patch to resolve terraform backend S3 issues
      # Reference: https://github.com/hashicorp/terraform/issues/36704
      AWS_RESPONSE_CHECKSUM_VALIDATION: "when_required"
      AWS_REQUEST_CHECKSUM_CALCULATION: "when_required"
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug
        run: |
          pwd
          ls -lrst

      - name: Write OCI Key File
        run: |
          echo "$OCI_KEY_FILE_CONTENT" > oci_api_key.pem
          chmod 600 oci_api_key.pem

      - name: Write VM SSH Private Key
        run: |
          echo "$VM_SSH_PRIVATE_KEY" > ./id_rsa
          chmod 600 ./id_rsa
        env:
          VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}

      - name: Debug Again
        run: |
          pwd
          ls -lrst

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.auto.tfvars"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="terraform.auto.tfvars"